### PR TITLE
make storage size parametrizable

### PR DESCRIPTION
**Pull request by nicolasochem**
My immediate need is to deploy an archive node; I need 300Gi of storage.

### CODE REVIEW

**Review by elric1 — CHANGES_REQUESTED** [review]
One comment that I have is that perhaps the size should be shared between the two types of node because I get the impression that it's really the `tezos-node` container that needs the space---and it's the size of the chain that drives the requirement.

**Comment by nicolasochem** [comment]
Not always, for example you could have a sentry model where your important baker node is running in private node and protected by sentries. You may want an archive node in the core of your topology, but the sentries should be rolling since they are just passing p2p messages along.
You could even be defining custom node types and helm would create statefulsets. In doubt, I'd say let us give ourselves flexibility.

**Review by harryttd — APPROVED** [review]

**Comment by elric1** [comment]
In this case, though, wouldn't you want to attach the storage size to the instance rather than the statefulset definition?

**Review by elric1 — APPROVED** [review]
We chatted offline and I'm convinced now.

**Pull request merged**
